### ISSUE TITLE
[Bug] Fix Footer 

### ISSUE THREAD

**Issue by riteshsonawane1372** [DIEMS-HUB/IETE-Website#108]
**To Reproduce**

Check `Core team` page
make footer fixed/sticky
![image](https://github.com/DIEMS-HUB/IETE-Website/assets/72307121/4ec95eaf-fd89-4e3c-8688-d91d8bb8db70)

**Comment by Akshayp02** [comment]
I would like to work on this issue, can you assign me this issue to explore it .

**Comment by Prathamesh180** [comment]
I want to solve it, but didn't get what changes are need to be done.

**Comment by adityawalture** [comment]
I am interested to solve
