### ISSUE TITLE
[Bug] Current Footer is Fixed

### ISSUE THREAD

**Issue by amanpandey3956** [DIEMS-HUB/IETE-Website#114]
## Description
![image](https://github.com/DIEMS-HUB/IETE-Website/assets/95525490/9aac7cbd-15a8-403d-a444-8730f124de55)
The current footer is fixed, we need to make it appear when end-user scroll down
**Bug Description:**
A clear and concise description of the bug.

## Reproduction Steps

**To Reproduce:**

Visit The root url of the website

## Expected Behavior

**Expected behavior:**

## Screenshots

**Screenshots:**
If applicable, add screenshots to help explain the problem.

## Environment Details

**Desktop (if applicable):**
- **OS:** [e.g., Windows 10, macOS]
- **Browser:** [e.g., Chrome, Firefox]
- **Version:** [e.g., 92.0.4515.131]

**Smartphone (if applicable):**
- **Device:** [e.g., iPhone 12]
- **OS:** [e.g., iOS 14]
- **Browser:** [e.g., Safari, Chrome]
- **Version:** [e.g., 14.7]

## Additional Context

**Additional context:**
Add any other relevant context about the problem here. For instance, details about workarounds you've tried, the frequency of the issue, or any specific conditions that trigger the bug.

**Comment by amanpandey3956** [comment]
@adityasimant Can you assign me this issue? would love to work on it. Do add a label of `Hacktoberfest`

**Comment by riteshsonawane1372** [comment]
@amanpandey3956 closing this issue.
