### ISSUE TITLE
Change the width of core team members card to fit all.

### ISSUE THREAD

**Issue by adityasimant** [DIEMS-HUB/IETE-Website#118]
## Problem Description
Each Row of the Core Team consists of 3 people, causing one member to be isolated at the end.

## Proposed Solution
Go to the Projectcards.js file and adjust each card to a length so that in each row there are 4 or 5 members. ( Set the appropriate width to the card using its className "project-card-view".

## Additional context 
please mention the issue in the PR and submit with screenshots.

**Comment by Shubbu-07** [comment]
Hey, I would like to fix this issue. Please assign me...

**Comment by Shraddhabghule** [comment]
assign me ...

**Comment by adityasimant** [comment]
closing as complete
