### ISSUE TITLE
Adding Event in Events.js

### ISSUE THREAD

**Issue by adityasimant** [DIEMS-HUB/IETE-Website#119]
## Problem Description

We have an upcoming event <b>MicroMaster: 8051 Microcontroller masterclass</b> which will be a workshop for 3rd year EnTC students where they can learn about 8051 Microcontrollers. Which is yet to be added in the event section.

## Proposed Solution

1. Create a new card below the "A New Start". ( can copy the above card)
2. Give a suitable Title and Description and add the upcoming label to it.
3. Make a PR with a screenshot of the output.

**Comment by 08Uzair** [comment]
Please assign this to me

**Comment by Shraddhabghule** [comment]
I would like to do please assign me

**Comment by ianujvarshney** [comment]
Can I work on this issue @adityasimant?

**Comment by adityasimant** [comment]
@ianujvarshney This issue has already been assigned to a fellow associate. However, you can wait for upcoming issues or create an issue enhancing the webpage.
