### ISSUE TITLE
Add events section in homepage

### ISSUE THREAD

**Issue by adityasimant** [DIEMS-HUB/IETE-Website#120]
Add a section on the homepage "Check out our recent events!" which should have a title, description and a button that redirects to "/events".

**Comment by Snowfall22** [comment]
interested, pls assign this to me

**Comment by GaneshNarwade** [comment]
I would like to fix this one, plz assign this to me

**Comment by ianujvarshney** [comment]
- can i work on this issue @adityasimant ?

**Comment by adityasimant** [comment]
Sure. Just add a button below the homepage logo that says view events and redirect it to events page
