### ISSUE TITLE
Change default Title 

### ISSUE THREAD

**Issue by riteshsonawane1372** [DIEMS-HUB/IETE-Website#30]
**Is your feature request related to a problem? Please describe.**

Add Favicon change the default react favicon and also change the title

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by the9esperanto** [comment]
Can I be allowed to resolve the Issue: Change Favicon and default Title in your project titled "IETE-WEBSITE"? Also, it would be of great help if you describe more changes you want (What type of title and icon are you considering). Please assign.

**Comment by riteshsonawane1372** [comment]
@the9esperanto  create a favicon that follows the current theme, the favicon can be a character (Like "I") or a symbol, for title keep it "IETE-DIEMS". Refer https://io.weekybinge.xyz/

**Comment by the9esperanto** [comment]
![icon](https://github.com/DIEMS-HUB/IETE-Website/assets/121279876/bb6fed2b-5e82-48da-b524-7b97a66737d7)
Will this be okay?

**Comment by adityasimant** [comment]
Hey @the9esperanto, we really appreciate you contributing to the project. However, it is the official student forum website and we have a whole design team for creating the icons. However, you can check out other future issues that need backend engineering. For now, I have to remove you from this issue. Thank you again.

**Comment by adityasimant** [comment]
If you want you can edit the title of the project to IETE DIEMS and make a pull request. Make sure to only push the index.html . I am assigning you the issue again. good luck. If you have any questions ask here before making the PR.

**Comment by adityasimant** [comment]
I am creating another issue to edit the favicon
