### ISSUE TITLE
[BUG] Core team page is crashing 

### ISSUE THREAD

**Issue by riteshsonawane1372** [DIEMS-HUB/IETE-Website#37]
The /coreteams page is crashing @adityasimant

**Comment by adityasimant** [comment]
Working on it

**Comment by riteshsonawane1372** [comment]
@adityasimant I deployed the website the error is still there. If this continue we need to build the complete website in html css and js.

**Comment by adityasimant** [comment]
The website deployed is not the latest. Make sure you build the correct version.

**Comment by riteshsonawane1372** [comment]
LG @adityasimant
