### ISSUE TITLE
[Bug] Change "WeMakeDev" in readm

### ISSUE THREAD

**Issue by riteshsonawane1372** [DIEMS-HUB/IETE-Website#54]
`WeMakeDev` -> `IETE-Website`
![image](https://github.com/DIEMS-HUB/IETE-Website/assets/72307121/7c0ff119-d54e-4576-af98-e8c37774f146)

**Comment by Akshayp02** [comment]
hey can you assign me this issue

**Comment by adityasimant** [comment]
Closing this as complete
