### ISSUE TITLE
Create a JoinUs page

### ISSUE THREAD

**Issue by adityasimant** [DIEMS-HUB/IETE-Website#78]
**Is your feature request related to a problem? Please describe.**
More of an enhancement we need a JoinUs page that links to the Google form to join the IETE DIEMS Student Forum. For now, we don't have a form so just Create a Page.

**Describe the solution you'd like**
1. Create a js file in `./src/components`  `JoinUs.js` that returns a Jsx element. If you want you can take a reference from other src components.
2. Include the `JoinUs.js` in App.js by importing it in `App.js` and append it to the Router so it can be located. It should look like:
```Javascript
      <Router>
        <NavBar />
        <Routes>
          <Route path="/" element={<Home />} />
          <Route path="/events" element={<Events />} />
          <Route path="/coreteam" element={<CoreTeam />} />
          <Route path="/about" element={<About />} />
          <Route path="/join" element={<JoinUs />} />
          <Route path="*" element={<Navigate to="/" />} />
        </Routes>
        <Footer/>
      </Router>
```
4. In `JoinUs.js`  include an Attractive Heading eg. Join Us in Empowering Tomorrow!
5. Write some context about our work and the benefits of joining.
6. Include a `Button` that says "Join IETE Student Forum" and don't provide any functionality to that button for now.
7. Test the result on a Desktop as well as in Mobile mode to check responsiveness.
8. Commit and push the code for review

**Additional context**
Contact maintainers for any help: adityasimant88@gmail.com

**Comment by Shubbu-07** [comment]
I'm interested & would like to work on **#78**

**Comment by Shubbu-07** [comment]
Hey, I've successfully completed #78.
