### ISSUE TITLE
Fix the PR and issue templates

### ISSUE THREAD

**Issue by adityasimant** [DIEMS-HUB/IETE-Website#85]
The current template has too much unnecessary text. Use markdown and keep it simple.

**Comment by ianujvarshney** [comment]
- I can work on this issue could you please assign me ?

**Comment by adityasimant** [comment]
Mention the issue number in the PR and keep the template professional and simple.

**Comment by ianujvarshney** [comment]
I just see your template of [issue](https://github.com/DIEMS-HUB/IETE-Website/tree/main/.github/ISSUE_TEMPLATE). where is First one PR Template?

**Comment by adityasimant** [comment]
We currently don't have a template for PRs as you might have noticed. We only have issue templates. You might have to create a new PR template and improve the issue template.
