### ISSUE TITLE
Changing the initial react template

### ISSUE THREAD

**Issue by adityasimant** [DIEMS-HUB/IETE-Website#86]
Change the initial boilerplate text of the website when it is shared. 
The Text "This website was created using create-react-app" Should be changed to the IETE description.

Use `react-helmet-async` for that install it `npm install react-helmet-async`

```import React from 'react';
import { Helmet } from 'react-helmet-async';

function SocialMeta() {
  return (
    <div>
      <Helmet>
        <title>Your Page Title</title>
        <meta name="description" content="Description of your page" />
        <meta property="og:title" content="Your Website Title" />
        <meta property="og:description" content="Description of your website" />
        <meta property="og:image" content="URL to the image you want to display" />
        <meta property="og:url" content="URL of your website" />
        <meta property="og:type" content="website" />
      </Helmet>
      {/* Your page content */}
    </div>
  );
}

export default SocialMeta;
 ```

Include in the Root 
`<Route path="/socialmeta-page" component={SocailMeta} />`

**Comment by ianujvarshney** [comment]
Can you Assign this bug for me ?

**Comment by ianujvarshney** [comment]
Are you need this change also in Index.html File? Could you tell me more about ? Check in [SocialMeta File](https://github.com/ianujvarshney/IETE-Website/blob/SocialMeta/src/components/SocialMeta.js)

**Comment by riteshsonawane1372** [comment]
@ianujvarshney Check this pr https://github.com/DIEMS-HUB/IETE-Website/pull/93/files and make changes which are mentioned in the review. If you need more help pls let me know

**Comment by ianujvarshney** [comment]
> @ianujvarshney Check this pr https://github.com/DIEMS-HUB/IETE-Website/pull/93/files and make changes which are mentioned in the review. If you need more help pls let me know
I also did same changes in that but i am asking you need this change in index.html file. Check it upper Link i did mention.

**Comment by riteshsonawane1372** [comment]
No

**Comment by ianujvarshney** [comment]
> No
> 

I did open a pr please check it. Is there any issue on that https://github.com/DIEMS-HUB/IETE-Website/pull/105
